
#端口号
server:
  port: 7510

spring:
  application:
    name: fund-cloud
  #数据源配置
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    driver-class -name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.193.26:3306/chat?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8



#mybatisPlus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    jdbc-type-for-null: NULL
    lazy-load-trigger-methods:
      - true
    aggressive-lazy-loading: true
    cache-enabled: true
    call-setters-on-nulls: true
  #放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations:
    - classpath:mapper/*Mapper.xml




